### ISSUE TITLE
Verify Vault download

### ISSUE THREAD

**Issue by moretea** [jcolemorrison/vault-on-aws#2]
Use e.g. sha256sum to verify the downloaded Vault binary.

**Comment by jcolemorrison** [comment]
Wow, good catch @moretea.  Thanks for pointing that out!  I'll add it to the todo list 👍

**Comment by jcolemorrison** [comment]
The vault download is now verified!  relevant commit: https://github.com/jcolemorrison/vault-on-aws/commit/73cd8a1ae58382439c11a62dc212b2049bec7a9b

**Comment by moretea** [comment]
Awesome :)
